package org.bfil.euler

import org.bfil.euler._

object Problem2 extends Problem {
  
  val name = "Even Fibonacci numbers"
  val description =
    """
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	
  	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    """
  val solution = 4613732
  
  // Parameters
  val max = 4000000
  
  def solve() =
    fibs.filter( _ % 2 == 0 ).takeWhile( _ < max ).sum
}